<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.xpdojo</groupId>
    <artifactId>bank-account-kata</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <!-- 这里只需要引入这一个聚合包，Maven 会自动下载 api, engine, params 等所有子模块 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
        <!-- AssertJ 也由 Maven 统一管理 -->
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.10.0</version>
            <scope>test</scope>
        </dependency>
        <!-- Spring Boot Web 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>3.2.4</version>
        </dependency>

        <!-- 可选：让接口测试更方便 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>3.2.4</version>
            <scope>test</scope>
        </dependency>

        <!-- Mockito依赖  -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.16.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.16.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- 用于运行测试的插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>
            <!-- 用于生成测试覆盖率报告文件的插件 -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 自动创建目录，verify前必经过程 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>prepare-jmeter-results</id>
                        <phase>prepare-package</phase> <!-- 在 verify 之前执行 -->
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <mkdir dir="${basedir}/target/jmeter-results/html"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <!-- Newman API 测试 -->
                    <execution>
                        <id>newman-test</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>newman</executable>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <arguments>
                                <argument>run</argument>
                                <argument>Bank_Account_API_Tests.postman_collection.json</argument>
                                <argument>-e</argument>
                                <argument>Local.postman_environment.json</argument>
                                <argument>-r</argument>
                                <argument>html</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <!-- JMeter 性能测试 -->
                    <execution>
                        <id>jmeter-performance-test</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>jmeter</executable>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <arguments>
                                <argument>-n</argument>
                                <argument>-t</argument>
                                <argument>${basedir}/src/test/jmeter/BankAccount_LoadTest.jmx</argument>
                                <argument>-l</argument>
                                <argument>${basedir}/target/jmeter-results/results.jtl</argument>
<!--                                <argument>-e</argument>-->
<!--                                <argument>-o</argument>-->
<!--                                <argument>${basedir}/target/jmeter-results/html</argument>-->
                            </arguments>
                        </configuration>
                    </execution>
                    <!-- JMeter 性能测试 -g参数从.jtl文件生成报告 -->
                    <execution>
                        <id>jmeter-generate-report</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>jmeter</executable>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <arguments>
                                <argument>-g</argument>
                                <argument>${basedir}/target/jmeter-results/results.jtl</argument>
                                <argument>-o</argument>
                                <argument>${basedir}/target/jmeter-results/html</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- 添加JMeter插件 -->
<!--            <plugin>-->
<!--                <groupId>com.lazerycode.jmeter</groupId>-->
<!--                <artifactId>jmeter-maven-plugin</artifactId>-->
<!--                <version>3.12.0</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>jmeter-tests</id>-->
<!--                        <phase>integration-test</phase>-->
<!--                        <goals>-->
<!--                            <goal>jmeter</goal>-->
<!--                        </goals>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--                <configuration>-->
<!--                    &lt;!&ndash; 指定 JMeter 测试脚本存放目录 &ndash;&gt;-->
<!--                    <testFilesDirectory>${basedir}/src/test/jmeter</testFilesDirectory>-->
<!--                    &lt;!&ndash; 指定结果输出目录 &ndash;&gt;-->
<!--                    <resultsDirectory>${basedir}/target/jmeter-results</resultsDirectory>-->
<!--                </configuration>-->
<!--            </plugin>-->
            <!-- Maven自启动服务 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <id>start-spring-boot</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <wait>1000</wait> <!-- 等待服务启动的最大毫秒数 -->
                            <maxAttempts>10</maxAttempts>
                            <fork>true</fork>  <!-- 关键：在独立进程中启动 -->
<!--                            <skip>false</skip>-->
<!--                            <jmxPort>9002</jmxPort>   &lt;!&ndash; 使用一个未占用的端口 &ndash;&gt;-->
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-spring-boot</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>
</project>